export const GET_VM_MESSAGES_START = "GET_VM_MESSAGES_START";
export const GET_VM_MESSAGES_SUCCESS = "GET_VM_MESSAGES_SUCCESS";
export const GET_VM_MESSAGES_ERROR = "GET_VM_MESSAGES_ERROR";

export const START_VM_MESSAGE_UPDATE = "START_VM_MESSAGE_UPDATE";
export const VM_MESSAGE_UPDATE_SUCCESS = "VM_MESSAGE_UPDATE_SUCCESS";
export const VM_MESSAGE_UPDATE_ERROR = "VM_MESSAGE_UPDATE_ERROR";

export const GET_VM_BOXES_START = "GET_VM_BOXES_START";
export const GET_VM_BOXES_SUCCESS = "GET_VM_BOXES_SUCCESS";
export const GET_VM_BOXES_ERROR = "GET_VM_BOXES_ERROR";
